# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a2081666cc98076e58fa1197053fcd0e67b54d904d88f1f13f5ab97a3177b6e794b486a5bfa31651a19b5c7bd70713763cefaa54758770baa1e0293dbfd8819

test:
  secret_key_base: e3fc6c16ed6d694f62d236e57df7444cfae80f8d0c5106bd5330eedbc7687fced047a5d514cbfdff7acf7c04afcb4d0a7578a3458e30acf978310965e35bcecf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
