# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd4486f20f42cf3c9aa2be4072976c349d3cf60be22631902d7d1213300b4cf65873c409bad8e18178865a51338718841198c3fce0476eeba5c5a3486bd293b7

test:
  secret_key_base: 5ec00b4f9b696c607be2da8ddd6e57e2a46614b7ea062a2b7fa2fa109b0290619267b54663ac2f3794369a4bb79b7f3327516ce0bc4922a9795de1f460dd2dbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
